### PR TITLE
feat!: robustify parser_v2 and add sanitize_cells to the library API

### PR DESCRIPTION
**Pull request by PeterStaar-IBM**
## Resolves

1. https://github.com/DS4SD/docling/issues/434
2. https://github.com/DS4SD/docling-parse/issues/59
3. https://github.com/DS4SD/docling/issues/445
4. https://github.com/DS4SD/docling/issues/253
5. https://github.com/DS4SD/docling/issues/285

### CODE REVIEW

**Comment by cau-git** [comment]
@PeterStaar-IBM Let's push this out and continue on another PR for the ligatures. It is a massive improvement already as is.

**Comment by hamedf62** [comment]
kindly update about the RTL support release schedule

**Comment by PeterStaar-IBM** [comment]
> kindly update about the RTL support release schedule

Yes, it should be taken care of!

**Review by cau-git — APPROVED** [review]
🚀 🚢

**Pull request merged**
